name: Test Ubicloud Prod Runners

on:
  push:
    branches: [checkout-benchmark]
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  test:
    # container:
    #   image: ubuntu:latest
      # options: --init
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubicloud-standard-2-ubuntu-2404
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2404
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-premium-2-ubuntu-2404
          - ubicloud-premium-2-ubuntu-2204
          - ubicloud-premium-2-ubuntu-2404
          - ubicloud-premium-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2404
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2404
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-premium-2-ubuntu-2404
          - ubicloud-premium-2-ubuntu-2204
          - ubicloud-premium-2-ubuntu-2404
          - ubicloud-premium-2-ubuntu-2204
          - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.runs-on }}
    steps:
      - name: github curl
        run: |
          echo "Testing download speed from GitHub..." >> $GITHUB_STEP_SUMMARY
          curl -o /dev/null -w "%{speed_download} bytes/s, %{time_total}s\n" -L https://github.com/git/git/archive/refs/tags/v2.45.0.tar.gz >> $GITHUB_STEP_SUMMARY
    
      - name: mtr
        run: |
          echo "Testing network latency and packet loss to github.com..." >> $GITHUB_STEP_SUMMARY
          sudo mtr -rwbzc 200 -P 443 -T github.com >> $GITHUB_STEP_SUMMARY
      - name: checkout
        uses: actions/checkout@v6
      - name: check kernel
        run: uname -a
      - run: ./net-debug.sh 10
      - run: cat netdebug-output/summary.md >> $GITHUB_STEP_SUMMARY

